<a href="https://colab.research.google.com/github/norannali/Data-Science-ML-Exercises/blob/main/NumPy_Revision_and_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
#The basics
print("Array Shape : ",a.shape)
print("the number of axes (dimensions) of the array : ",a.ndim)
print("the total number of elements of the array : ",a.size)
print("an object describing the type of the elements in the array : ",a.dtype)
print("the size in bytes of each element of the array : ",a.itemsize)

Array Shape :  (3, 5)
the number of axes (dimensions) of the array :  2
the total number of elements of the array :  15
an object describing the type of the elements in the array :  int64
the size in bytes of each element of the array :  8


# **Array creation**

In [5]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [6]:
c=np.array([(1.5,2,3),(4,5,6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
arr1=np.zeros((3,4))
arr2=np.ones((1,3,4),dtype=np.int16)
arr3=np.empty((2,3))
print(arr1)
print("="*50)
print(arr2)
print("="*50)
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [8]:
arr4=np.arange(10,30,5)
arr5=np.linspace(0,2,9)  #9 numbers from 0 to 2 # contain the start point +the end point + the number of elements
print(arr4)
print("="*50)
print(arr5)

[10 15 20 25]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [9]:
np.random.random((2,3))

array([[0.32499994, 0.55631361, 0.7899968 ],
       [0.77464554, 0.73617417, 0.3978321 ]])

In [10]:
np.random.rand(2,3)   #number between 0 and 1

array([[0.39210851, 0.31418619, 0.77586682],
       [0.13175364, 0.27697734, 0.23684006]])

In [11]:
np.random.randn(2,3) #number from normal distribution

array([[-0.48334785,  0.89903406,  0.65586773],
       [-1.86994443,  1.58495995, -0.91121694]])

In [12]:
np.random.randint(2,10)

3

In [13]:
np.random.randint(2,10,size=8)

array([7, 8, 3, 6, 4, 7, 7, 6])

In [14]:
np.random.randint(2,10,size=(2,4))

array([[4, 8, 4, 5],
       [5, 4, 9, 5]])

In [15]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [16]:
np.full((2,2),[1,2])

array([[1, 2],
       [1, 2]])

In [17]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty((2,3),dtype=int)

array([[4602378840627170906, 4606272998471563699, 4604082750868861345],
       [4611100300225787782, 4609816844198926673, 4606382732100145152]])

# **Operations in array**

In [19]:
a=np.arange(0,12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
b=a.reshape((3,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
a=b.ravel() #convert into 1d array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
c=b.transpose()
print(c)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [23]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [24]:
a=np.array([[1,1],
           [0,1]])
b=np.array([[2, 0],
            [3, 4]])
#Operations
print(a+b)
print("="*50)
print(a-b)
print("="*50)
print(a*b)
print("="*50)
print(f"Matrix Product by  arr1@arr2  :")
print(a@b)
print("="*50)
print(f"Matrix Product by  arr1.dot(arr2)  :")
print(a.dot(b))

[[3 1]
 [3 5]]
[[-1  1]
 [-3 -3]]
[[2 0]
 [0 4]]
Matrix Product by  arr1@arr2  :
[[5 4]
 [3 4]]
Matrix Product by  arr1.dot(arr2)  :
[[5 4]
 [3 4]]


In [25]:
#Increment & Decrement
arr=np.arange(1,5)
print(arr)

[1 2 3 4]


In [26]:
arr+=2
print(arr)

[3 4 5 6]


In [27]:
arr-=1
print(arr)

[2 3 4 5]


**Universal Functions**

In [28]:
a=np.arange(1,5)
print(a)

[1 2 3 4]


In [29]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [30]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [32]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Aggregate Function**

In [33]:
aa=np.array([1,2,5,5.6,6.2,4.9,7.3,7.9])
aa

array([1. , 2. , 5. , 5.6, 6.2, 4.9, 7.3, 7.9])

In [34]:
np.max(aa)

7.9

In [35]:
np.argmax(aa) #index of the max num

7

In [36]:
np.mean(aa)

4.9875

In [37]:
aa.std()

2.250243042428973

In [38]:
z = np.array([
    [2, 1, 0],
    [5, 6, 7],
    [3, 8, 9]
])

In [39]:
z[[0,1],[0,2]]

array([2, 7])

In [40]:
z[::1]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

In [41]:
z[0:3,0:3]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

In [42]:
z[:]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

# **Indexing**
Access Array Elements Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [43]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [44]:
print(arr[2] + arr[3])

7


In [45]:
# Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])


2nd element on 1st row:  2
5th element on 2nd row:  10


In [46]:
# Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 1])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5


# **NumPy Array Slicing**
We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [48]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) # 0 : 2 > arrays
print('-'*50)
print(arr[0:1, 1:5])
print("="*50)
arr2=np.array([[1,2,3,4,5],
              [10,20,30,40,50],
              [100,200,300,400,500]])
print(arr2[0:2, 1:4])
print('-'*50)
print(arr2[1:3,2:5])

[[2 3 4]
 [7 8 9]]
--------------------------------------------------
[[2 3 4 5]]
[[ 2  3  4]
 [20 30 40]]
--------------------------------------------------
[[ 30  40  50]
 [300 400 500]]


In [49]:
## Joining Array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# **Join & Split Arrays**

In [61]:
#Join
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

In [60]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [62]:
np.row_stack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
#Split
a=np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [64]:
[b,c]=np.hsplit(a,2)
print(b)
print('-'*20)
print(c)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
--------------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [65]:
[b,c]=np.vsplit(a,2)
print(b)
print('-'*20)
print(c)

[[0 1 2 3]
 [4 5 6 7]]
--------------------
[[ 8  9 10 11]
 [12 13 14 15]]


In [69]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
[x,y,z]=np.split(a,[1,3],axis=1)
print(x)   #0 to 1(exclude)
print('-'*20)
print(y)   #1 to 3(exclude)
print('-'*20)
print(z)   #3 to end

[[ 0]
 [ 4]
 [ 8]
 [12]]
--------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
--------------------
[[ 3]
 [ 7]
 [11]
 [15]]


In [68]:
[x,y,z]=np.split(a,[2,3],axis=0)
print(x)
print('-'*20)
print(y)
print('-'*20)
print(z)

[[0 1 2 3]
 [4 5 6 7]]
--------------------
[[ 8  9 10 11]]
--------------------
[[12 13 14 15]]


**View Vs Copies**

In [70]:
a=np.array([1,2,3,4])
b=a

In [71]:
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [73]:
#We find that array a and b are change becouse that a view b
a[2]=0
print(a)
print(b)

[1 2 0 4]
[1 2 0 4]


In [74]:
c=a[0:2]
print(a)
print(c)

[1 2 0 4]
[1 2]


In [75]:
a[0]=5
print(a)
print(c)

[5 2 0 4]
[5 2]


In [76]:
a=np.array([1,2,3,4])
c=a.copy()
print(a)
print(c)

[1 2 3 4]
[1 2 3 4]


In [77]:
a[3]=7
print(a)
print(c)

[1 2 3 7]
[1 2 3 4]


# **Numpy_exercise**

**Q_1: create 2D-array that contain even numbers between 0-18...??**

In [50]:
arr=np.arange(0,18,2).reshape(3,3)
arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

**Q_2: Replace the negative values with 0 in random array that has value in range (-6,6)**

In [51]:
arr=np.random.randint(-6,6,10)
print(arr)
arr[arr<0]=0
print("After Mapping : ",arr)

[-1  1 -5 -3 -1  1  0 -1 -2  0]
After Mapping :  [0 1 0 0 0 1 0 0 0 0]


**Q_3 : How to compute ((A+B)*(-A/2)) ? where A,B random array**

In [52]:
a=np.random.randint(0,10,(3,4))
b=np.random.randint(0,10,(3,4))
print(a)
print(b)

[[5 4 8 9]
 [2 9 4 5]
 [2 7 6 9]]
[[9 5 4 5]
 [9 0 2 5]
 [4 1 9 2]]


In [53]:
print(((a+b)*(-a/2)))

[[-35.  -18.  -48.  -63. ]
 [-11.  -40.5 -12.  -25. ]
 [ -6.  -28.  -45.  -49.5]]


**Q_4: How to concatenate two arrays horizontally..?**

In [54]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(np.concatenate((arr1,arr2),axis=0))

[ 1  2  3  4  5  6  7  8  9 10]


**Q_5: Create a random vector of size 3x3 and sort values in Its columns**

In [55]:
arr=np.array([[6,9,3,8,5,1,7,4,2]]).reshape(3,3)
print(arr)
print("="*30)
print("Sort by Columns : ")
print(np.sort(arr,axis=0))
print("="*30)
print("Sort by Rows : ")
print(np.sort(arr,axis=1))


[[6 9 3]
 [8 5 1]
 [7 4 2]]
Sort by Columns : 
[[6 4 1]
 [7 5 2]
 [8 9 3]]
Sort by Rows : 
[[3 6 9]
 [1 5 8]
 [2 4 7]]
