<a href="https://colab.research.google.com/github/norannali/Data-Science-ML-Exercises/blob/main/NumPy_Revision_and_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a=np.arange(15).reshape(3,5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
#The basics
print("Array Shape : ",a.shape)
print("the number of axes (dimensions) of the array : ",a.ndim)
print("the total number of elements of the array : ",a.size)
print("an object describing the type of the elements in the array : ",a.dtype)
print("the size in bytes of each element of the array : ",a.itemsize)

Array Shape :  (3, 5)
the number of axes (dimensions) of the array :  2
the total number of elements of the array :  15
an object describing the type of the elements in the array :  int64
the size in bytes of each element of the array :  8


# **Array creation**

In [11]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [12]:
c=np.array([(1.5,2,3),(4,5,6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [15]:
arr1=np.zeros((3,4))
arr2=np.ones((1,3,4),dtype=np.int16)
arr3=np.empty((2,3))
print(arr1)
print("="*50)
print(arr2)
print("="*50)
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [18]:
arr4=np.arange(10,30,5)
arr5=np.linspace(0,2,9)  #9 numbers from 0 to 2
print(arr4)
print("="*50)
print(arr5)

[10 15 20 25]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [24]:
a=np.array([[1,1],
           [0,1]])
b=np.array([[2, 0],
            [3, 4]])
#Operations
print(a+b)
print("="*50)
print(a-b)
print("="*50)
print(a*b)
print("="*50)
print(f"Matrix Product by  arr1@arr2  :")
print(a@b)
print("="*50)
print(f"Matrix Product by  arr1.dot(arr2)  :")
print(a.dot(b))

[[3 1]
 [3 5]]
[[-1  1]
 [-3 -3]]
[[2 0]
 [0 4]]
Matrix Product by  arr1@arr2  :
[[5 4]
 [3 4]]
Matrix Product by  arr1.dot(arr2)  :
[[5 4]
 [3 4]]


# **Indexing**
Access Array Elements Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [25]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [26]:
print(arr[2] + arr[3])

7


In [28]:
# Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])


2nd element on 1st row:  2
5th element on 2nd row:  10


In [33]:
# Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 1])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5


# **NumPy Array Slicing**
We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [43]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) # 0 : 2 > arrays
print('-'*50)
print(arr[0:1, 1:5])
print("="*50)
arr2=np.array([[1,2,3,4,5],
              [10,20,30,40,50],
              [100,200,300,400,500]])
print(arr2[0:2, 1:4])
print('-'*50)
print(arr2[1:3,2:5])

[[2 3 4]
 [7 8 9]]
--------------------------------------------------
[[2 3 4 5]]
[[ 2  3  4]
 [20 30 40]]
--------------------------------------------------
[[ 30  40  50]
 [300 400 500]]


In [44]:
## Joining Array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# **Numpy_exercise**

**Q_1: create 2D-array that contain even numbers between 0-18...??**

In [47]:
arr=np.arange(0,18,2).reshape(3,3)
arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

**Q_2: Replace the negative values with 0 in random array that has value in range (-6,6)**

In [49]:
arr=np.random.randint(-6,6,10)
print(arr)
arr[arr<0]=0
print("After Mapping : ",arr)

[ 3  2 -2  5  1 -2 -5  2 -3  3]
After Mapping :  [3 2 0 5 1 0 0 2 0 3]


**Q_3 : How to compute ((A+B)*(-A/2)) ? where A,B random array**

In [50]:
a=np.random.randint(0,10,(3,4))
b=np.random.randint(0,10,(3,4))
print(a)
print(b)

[[9 3 8 6]
 [9 8 5 7]
 [0 2 3 1]]
[[8 4 8 8]
 [7 0 0 6]
 [4 5 5 1]]


In [52]:
print(((a+b)*(-a/2)))

[[-76.5 -10.5 -64.  -42. ]
 [-72.  -32.  -12.5 -45.5]
 [  0.   -7.  -12.   -1. ]]


**Q_4: How to concatenate two arrays horizontally..?**

In [57]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(np.concatenate((arr1,arr2),axis=0))

[ 1  2  3  4  5  6  7  8  9 10]


**Q_5: Create a random vector of size 3x3 and sort values in Its columns**

In [64]:
arr=np.array([[6,9,3,8,5,1,7,4,2]]).reshape(3,3)
print(arr)
print("="*30)
print("Sort by Columns : ")
print(np.sort(arr,axis=0))
print("="*30)
print("Sort by Rows : ")
print(np.sort(arr,axis=1))


[[6 9 3]
 [8 5 1]
 [7 4 2]]
Sort by Columns : 
[[6 4 1]
 [7 5 2]
 [8 9 3]]
Sort by Rows : 
[[3 6 9]
 [1 5 8]
 [2 4 7]]
